In [59]:
import snow.utils as sf
import pandas as pd
import numpy as np

In [4]:
data = sf.from_snow(schema='glue',query='select * from sydney_',to_df=False)

Using zans_role...
Established connection.
Querying zans_wh.zans_db.glue
Custom data:  (1365.0, 'https://www.zomato.com/sydney/sandoitchi-darlinghurst\n')

Connection succesfully closed.

In [23]:
df = pd.DataFrame(data,columns=['Id','url'])

In [12]:
from snap.snap import prepare_data

In [15]:
a,b = prepare_data('sydney')

Using all_data_viewer...
Established connection.
Querying load_wh.all_data.postgres
Custom data:  (593720, 1135, 'Melbourne', '8Bit', 'Swanston Street')

Connection succesfully closed.
Using all_data_viewer...
Established connection.
Querying load_wh.all_data.postgres
Custom data:  ('Balkan Seafood', 'Darlinghurst', '-33.88119518547905', '151.21783929064785', 'Sydney', 355)

Connection succesfully closed.
Using all_data_viewer...
Established connection.
Querying load_wh.all_data.postgres
Custom data:  (1412, 'Melbourne')

Connection succesfully closed.

In [33]:
new_df = b.merge(df,how='outer')
new_df.shape

(422, 7)

In [29]:
new_df.shape

(378, 7)

In [56]:
no_match = new_df[new_df.url.isnull()]

In [58]:
no_match

,Name,Branch,Latitude,Longitude,City,Id,url
0,Cafe Hernandez,Potts Point,-33.87596739999999,151.2251818,Sydney,305.0,NaN
25,Chilli and Spicy,Sydney,-33.87901,151.205284,Sydney,721.0,NaN
30,Aslan Coffee,St Peters,-33.90916048158275,151.17866831020294,Sydney,598.0,NaN
32,Burger Crave,Bondi Junction,-33.893581319666694,151.24936061099342,Sydney,1002.0,NaN
37,Messina Rosebery,Rosebery,-33.91800722848461,151.202953030639,Sydney,1326.0,NaN
46,Jimbaran Restaurant,Randwick,-33.9128240262787,151.2424297829012,Sydney,1460.0,NaN
47,Sergio's Trattoria and Pizzeria,Newtown,-33.90624878824236,151.18103401856294,Sydney,717.0,NaN
49,Edition Coffee Pop Up,Haymarket,-33.87861043778976,151.20125787452884,Sydney,1350.0,NaN
58,Royal Stacks,Chatswood,-33.79697800000001,151.18342199999998,Sydney,1311.0,NaN
62,Naya Cafe,Glebe,-33.88373991361573,151.19219737246564,Sydney,1031.0,NaN
68,The Colonial,Neutral Bay,-33.83014445815917,151.22191088394,Sydney,978.0,NaN
72,LL Wine and Dine,Potts Point,-33.87258791690379,151.2244697113561,Sydney,625.0,NaN
80,Tj Fresh Sushi,Ultimo,-33.883704,151.197038,Sydney,723.0,NaN
98,Treetop Cafe,Waterloo,-33.9035774224708,151.21333854391938,Sydney,634.0,NaN
128,Fishbowl,Darlinghurst,-33.88026175154544,151.21520536138786,Sydney,1131.0,NaN
141,Love Dem Apples,Steam Mill Lane,-33.878252,151.20181,Sydney,1405.0,NaN
154,Taste of Szechuan,Redfern,-33.89200498981941,151.21463136867058,Sydney,727.0,NaN
192,Fishbowl,Surry Hills,-33.88113909901242,151.20934741692238,Sydney,1132.0,NaN
196,Doughboy,Surry Hills,-33.890286133674294,151.213188340214,Sydney,1035.0,NaN
202,Cloud Thief,Sydney Westfield,-33.87008475253962,151.2093742389998,Sydney,1197.0,NaN
221,Cafe Birkenhead,Drummoyne,-33.85595600000001,151.16122699999997,Sydney,295.0,NaN
222,Dave's Deli,Sydney,-33.865073,151.208405,Sydney,1358.0,NaN
235,Cafe Kensington,Kogarah,-33.965633874695335,151.13361792759457,Sydney,637.0,NaN
245,Kawa Ramen,Haymarket,-33.879911,151.206066,Sydney,912.0,NaN
261,Mad Spuds Cafe,Surry Hills,-33.88806403774217,151.21318834023194,Sydney,730.0,NaN
263,Fishbowl,Manly,-33.79875829842885,151.28615515425628,Sydney,1133.0,NaN
265,Cream'd,Steam Mill Lane,-33.878368,151.201597,Sydney,1403.0,NaN
278,Cloud Thief,World Square,-33.87673000273751,151.20758252339294,Sydney,1196.0,NaN
312,Ben Gong's Tea and Bakery,Burwood,-33.87630647812326,151.1042799253928,Sydney,1515.0,NaN
326,Exotik Latin Cafe,Newtown,-33.89635986404664,151.18042247490138,Sydney,599.0,NaN
337,The Colonial,Darlinghurst,-33.87494403124188,151.21629433825203,Sydney,977.0,NaN
339,Chinatown Noodle Restaurant,Pyrmont,-33.870571,151.19565,Sydney,771.0,NaN
365,Bowl Bar by Berry 'N' Beans,Bondi,-33.8921831076459,151.27287285521902,Sydney,1228.0,NaN
380,Edition Coffee Roaster,Darlinghurst,-33.877557978248504,151.21573643879026,Sydney,1334.0,NaN
392,Restaurant Moon,Darlinghurst,-33.8783863632536,151.22266190246697,Sydney,1511.0,NaN
397,Sash Japanese,Sydney,None,None,Sydney,1717.0,NaN
403,Bar Ume,Surry Hills,-33.88705,151.215383,Sydney,1349.0,NaN